using System;
using System.Collections.Generic;
using System.Text;

namespace BMC
{
    public class BMCInfo
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string YoutubeLink { get; set; }
        public string MyText { get; set; }
        public string MyImage { get; set; }
        public string MyImage2 { get; set; }

    }
    public class Data
    {
        public List<BMCInfo> BMCdata { get; set; }

        public void Data_in()
        {
            BMCdata = new List<BMCInfo>();
            BMCdata.Add(new BMCInfo() { ID = 0, Name = "What’s the Business Model Canvas ?", MyImage2 = "Assets/BMC.png", YoutubeLink = "https://www.youtube.com/watch?v=QoAOzMTLP5s", MyText = "The Business Model Canvas (BMC) gives you the structure of a business plan without the overhead and the improvisation of a ‘back of the napkin’ sketch without  the fuzziness (and coffee rings) " + "\r\n" + "The Canvas has nine elements:" + "\r\n" + "1 - Customer Segments: Who are the customers? What do they think? See? Feel? Do?" + "\r\n" + "2 - Value Propositions: What’s compelling about the proposition? Why do customers buy, use?" + "\r\n" + "3 - Channels: How are these propositions promoted, sold and delivered? Why? Is it working?" + "\r\n" + "4 - Customer Relationships: How do you interact with the customer through their ‘journey’?" + "\r\n" + "5 - Revenue Streams: How does the business earn revenue from the value propositions?" + "\r\n" + "6 - Key Activities: What uniquely strategic things does the business do to deliver its proposition?" + "\r\n" + "7 - Key Resources: What unique strategic assets must the business have to compete?" + "\r\n" + "8 - Key Partnerships: What can the company not do so it can focus on its Key Activities?" + "\r\n" + "9 - Cost Structure: What are the business’ major cost drivers? How are they linked to revenue?" + "\r\n" + "The Canvas is popular with entrepreneurs and intrapreneurs for business model innovation. Fundamentally, I find it delivers three things:" + "\r\n" + "A. Focus: Stripping away the 40+ pages of ‘stuff’ in a traditional business plan, I’ve seen users of the BMC improve their clarify and focus on what’s driving the business (and what’s non-core and getting in the way)." + "\r\n" + "B. Flexibility: It’s alot easier to tweak the model and try things (from a planning perspective) with something that’s sitting on a single page." + "\r\n" + "Transparency: Your team will have a much easier time understanding your business model and be much more likely to buy in to your vision when it’s laid out on a single page." });
            BMCdata.Add(new BMCInfo() { ID = 1, Name = "Step 1 (of 9): Customer Segments", MyImage = "Assets/Customer-Segments.png", MyText = "For purposes of using the canvas you should make sure you can answer these questions:" + "\r\n" + "1. Segment Dimensions" + "\r\n" + "Do you have a single or multi-sided market? If you have a multi-sided market you’ll have at least as many segments as you have sides. An example of such a market is a media property like CNN.com: they have readers on the one side and advertisers on the other." + "\r\n" + "2. Segment Composition" + "\r\n" + "If the segment dimensions are the ‘macro’ analysis of your customer base, then looking within each segment at individual customer types as ‘Personas’ is the ‘micro’. As with economics, this is where most of action happens. You should be able to visualize these Personas- what kind of shoes do they wear? And you should understand what they think, see, feel, and do in your product area. Be sure to list both buyers and users of your product (many Personas will be both). " + "\r\n" + "3. Problems, Needs, Habits & Current Alternatives" + "\r\n" + "What job are you doing for the customer? What need are you fulfilling? There are no new behaviors- make sure that you can identify an existing need/problem and identify specific alternatives that your customer uses today. If you’re not sure, go out and observe, talk to some representative people. You’ll want to be able to clearly link your Value Propositions back to these in the next section." + "\r\n" + "Output: a list of Personas, organized by Customer Segment if you have more than one segment. I recommend trying to prioritize them- Who would you pitch first if you could only pitch one? Who next? And so forth…" + "\r\n" + "Notes: If you’re spending a lot of time on this first item, that’s OK (and it’s probably good). The Canvas is a tool, not a strategy and not all the nine blocks are equal. The pairing of Customer Segments and Value Propositions is really the ‘independent variable’ that should be driving everything else in your business model. When I use the Canvas in my Venture Design classes, we usually spend all of the first session (plus time for field research) on Customer Segments and Value Propositions." });
            BMCdata.Add(new BMCInfo() { ID = 2, Name = "Step 2 (of 9): Value Propositions", MyImage = "Assets/Value-Propositions.png", MyText = "Which of the Problems or Needs that you identified in your Personas are you fulfilling? What is unique about your Value Propositions and why does your customer prefer them to their Current Alternatives? You may have a whole lot of these- and that’s fine. When you’re getting going with this, jot them all done on a whiteboard, index card, Post-It, etc. But then rank them and you’ll probably want to winnow out all but the most critical. What things do you do that actually cause a customer to pick you over a competitor or alternative?" + "\r\n" + "For example, at Leonid, an enterprise software company I founded, we thought our largest customers worked with us because of the cost savings we offered and our knowledge about best practices. It turned out that was mostly wrong- reducing their time and risk to get new services to market was the most important. It’s not that the other things weren’t important, but they weren’t the top Value Proposition. That made a difference on how we sold the product and how we focused on operationalizing it for customers." + "\r\n" + "Output: a prioritized list of Value Propositions and linkages from each Personas to the VP’s relevant to them." + "\r\n" + "Notes: Again, this pairing is the key driver for most business models" + "\r\n" + "Maybe you feel like you’re in good shape on understanding the customer’s world but you don’t have any validation on whether the Value Propositions are clicking because this is a new venture? If you’re not sure, that’s OK and good for you for acknowledging the uncertainty! It’s the responsible thing to do. The key is to write down those assumptions, prioritize them, and figure out the quickest and cheapest way to prove or disprove them." });
            BMCdata.Add(new BMCInfo() { ID = 3, Name = "Step 3 (of 9): Channels", MyImage = "Assets/Channels.png", MyText = "Channels includes entities you use to communicate your proposition to your segments, as well as entities through which you sell product and later service customers. For example, if you sell bulbs for light houses and there’s a website all light house attendants purchase equipment, that site is a sales Channel. If you use Google AdWords, that’s a Channel, too (for getting attention). If you use a third party company to service the bulbs when they break, that’s also a Channel" + "\r\n" + "Output: a list of important Channels, linked to Personas or Segments if they differ substantially. Make notes on what steps are relevant for each- promotion, sales, service, etc. See Note this section for more structure on this." + "\r\n" + "Notes: Channels and the next item, Customer Relationships, define your interface with the Customer. It’s important to think all the way through the customer ‘journey’ in specific terms. For most businesses, the way they get a customer’s attention is different than the way they onboard them or support them over the long term. For this, I recommend the AIDA.OR framework (attention-interest-desire-action-onboarding-retention) and storyboarding your way through it." + "\r\n" + "Another consideration is whether your channels will give you enough visibility into the user. " });
            BMCdata.Add(new BMCInfo() { ID = 4, Name = "Step 4 (of 9): Customer Relationships", MyImage = "Assets/Customer-Relationships.png", MyText = "How does the customer interact with you through the sales and product lifecycle? Do they have a dedicated personal contact they see? Call? Is all the interaction over the web? Do they never see you at all but instead talk to a Channel? A few litmus test questions you may want to ask yourself at this point:" + "\r\n" + "– Can the Value Proposition be delivered to the Customer this way? All the way through from promotion, to sale, to post-sale service? (See AIDAOR above on this.)" + "\r\n" + "– Can you make the numbers work?" + "\r\n" + "– Is there a premium support product you need to create/test? Many companies, like Apple, have rejected the false choice of ‘Do we provide phone support or not?’ instead offering personal support for a reasonable charge." + "\r\n" + "Output: a description of Customer Relationships, with notes if they differ across Customers (between Segments or among Personas within a Segment) or across the customer journey." + "\r\n" + "Notes: If you’re a startup, be sure to document and review critical assumptions here. Also, the focal items are in a kind of specific order- you should validate your Segments and their relationship to the Propositions above all else. If this means you provide personal support in the early days to do discovery and validation of Segments and Propositions, that’s OK. You can subsequently test the Customer Relationship models. " });
            BMCdata.Add(new BMCInfo() { ID = 5, Name = "Step 5 (of 9): Revenue Streams", MyImage = "Assets/Revenue-Streams.png", MyText = "I won’t bore you with proclamations about the importance of revenue- you get it. If you have an existing business, this will be self-evident." + "\r\n" + "At this point, you should map Segments to Propositions to Revenue Streams. " + "\r\n" + "Output: a list of Revenue Streams, linked (mutually) to Personas (or Segments if the mappings are the same within a set of Personas) and Value Propositions" + "\r\n" + "Notes: If you have a startup or are re-engineering the business, this is a time to look at where you’re driving revenue and whether it aligns with the rest of your focal points. Are you charging on value? Perceived value? They say everyone loves their banker; hates their lawyer. Why is that? Is there an actionable analog in your business?" });
            BMCdata.Add(new BMCInfo() { ID = 6, Name = "Step 6 (of 9): Key Activities", MyImage = "Assets/Key-Activities.png", MyText = "These are the crucial things the business needs to do to deliver on its propositions and make the rest of the business work- for example, if selling through 3rd parties is part of the model, then activity around channel management is probably pretty important." + "\r\n" + "For a product-driven business, this probably includes ongoing learning about users and new techniques to build better product. If you’re focused on doing a bunch of things for a particular set of customers (ex: comprehensive IT for law offices), this probably includes maintaining superior expertise on the segment(s) and creating or acquiring products and services that are a good fit, whatever that entails. For an infrastructure business (ex: electric utility), it probably includes keeping the infrastructure working reliably and making it more efficient." + "\r\n" + "Outputs: a list of Key Activities linked to your business’ Value Propositions." + "\r\n" + "Notes: One question this analysis should raise for you is whether or not certain Activities and Resources are actually core, actually focal to your business, something you’ll want to think through ." });
            BMCdata.Add(new BMCInfo() { ID = 7, Name = "Step 7 (of 9): Key Resources", MyImage = "Assets/Key-Resources.png", MyText = "Key resources are the strategic assets you need in place, and you need in place to a greater or more targeted degree than your competitors. The Business Model Canvas proposes that there are three core business types: product, scope, and infrastructure. These tend to have similar types of Key Resources." + "\r\n" + "Outputs: a list of Key Resources linked to your business’ Key Activities." + "\r\n" + "Notes: Product-driven businesses have a differentiated product of some sort. Rovio, the company that makes the popular app Angry Birds, is such a company. Key Resources in product-driven businesses are typically key talent in critical areas of expertise and accumulated intellectual property related to their offering." + "\r\n" + "Scope-driven businesses create some synergy around a particular Customer Segment. For example, if you started a business that would take care of all the IT needs for law firms, that would be a scope-driven business. These businesses typically have key knowledge about their segment, a repeatable set of processes, and sometimes infrastructure, like service centers." + "\r\n" + "Infrastructure-driven businesses achieve economies of scale in a specific, highly repeatable area. Telecommunications is traditionally an infrastructure business. Retailers focused on retail, like Walgreens or Costco, are primarily infrastructure-driven businesses. The Key Resources for this type of business are, you guessed it, various types of physical or virtual infrastructure." + "\r\n" + "Let’s take a single product category: diapers. The Honest Company or another innovating around compostable or otherwise more environmentally friendly diapers would be a product-driven take on the category. Procter & Gamble which has a cradle-to-grave strategy for providing consumer products is a scope-based take; so are various baby-focused retailers. Kimberly-Clark (wood pulp) or DuPont (chemicals and polymers) are both infrastructure-based takes: diapers is just another way to sell something they produce at scale with relatively little differentiation." });
            BMCdata.Add(new BMCInfo() { ID = 8, Name = "Step 8 (of 9): Key Partnerships", MyImage = "Assets/Key-Partnerships.png", MyText = "At this point, hopefully the Canvas has helped you sharpen and articulate your business’ focal points. What Activities and Resources are important but not aligned with what’s uniquely strategy for you? What’s outside of your business type? Could partners do some of those? Why? Which?" + "\r\n" + "I recommend mapping Key Partners to Key Activities. If an activity is key, it’s still part of your business model. This is a way to denote which specific Partners are handling various Key Activities for you." + "\r\n" + "Output: a list of Key Partnerships with notes on their relationship to Key Activities." });
            BMCdata.Add(new BMCInfo() { ID = 9, Name = "Step 9 (of 9): Cost Structure", MyImage = "Assets/Cost-Strcuture.png", MyText = "You’ve worked to understand how your Key Activities drive your propositions and hence your revenue. How do they drive costs? Are those costs well aligned with the key Value Propositions? Are the costs more fixed or variable as you test different business models? Are they more linear with your scaling or more fixed? You’ll want to have these in mind as you tweak your model." + "\r\n" + "If there are major cost components that don’t map to a Key Activity, I’d take a closer look at those costs." + "\r\n" + "Output: a list of Cost Structure elements with notes on their relationship to Key Activities." });
        }
    }
}
